    SELECT SUBSTR(SYS_CONNECT_BY_PATH (NOMEPARC, '%'), 2) CSV
      FROM (SELECT NOMEPARC, ROW_NUMBER () OVER (ORDER BY NOMEPARC ) RN, 
                   COUNT (*) OVER () CNT 
              FROM TGFPAR) 
     WHERE RN = CNT
CONNECT BY RN=PRIOR RN + 1
START WITH RN = 1

oracle 11g
select LISTAGG(ename, '#') WITHIN GROUP (ORDER BY ename desc)  from emp;

select replace(wm_concat(ename),’,',’ / ‘) from emp

SELECT regexp_substr('1234,5678,890','[^,]+', 1, LEVEL) FROM dual
connect by regexp_substr('1234,5678,890', '[^,]+', 1, level) is not null;

  SELECT regexp_substr(CARACTERISTICAS,'[CHR(13)]+') FROM TGFPRO PRO WHERE CODPROD=6
  CONNECT BY regexp_substr(CARACTERISTICAS,'[CHR(13)]+') IS NOT NULL

REGEXP_REPLACE

  SELECT regexp_substr(CARACTERISTICAS,'[^CHR(13)]+'), CARACTERISTICAS FROM TGFPRO PRO WHERE CODPROD=6


CREATE OR REPLACE FUNCTION QUEBRACARACT (P_CODPROD IN NUMBER,P_CONTAGEM IN NUMBER)
RETURN VARCHAR2
IS


--CONTAGEM   INT;
P_LINHAS     CLOB;
BEGIN
  SELECT PR.CARACTERISTICAS INTO P_LINHAS
    FROM (
  SELECT REGEXP_SUBSTR (CARACTERISTICAS, '[^'||CHR (10)||']+', 1, LEVEL) AS CARACTERISTICAS, ROWNUM AS CONTAGEM
    FROM (
  SELECT CARACTERISTICAS, CODPROD FROM TGFPRO PRO) PRO
  WHERE PRO.CODPROD=P_CODPROD
  START WITH PRO.CODPROD=P_CODPROD
  CONNECT BY PRO.CODPROD=P_CODPROD AND LEVEL <= regexp_count(CARACTERISTICAS, CHR (10)) + 1) PR
  WHERE PR.CONTAGEM=P_CONTAGEM;
  
   RETURN P_LINHAS;
   EXCEPTION
   WHEN NO_DATA_FOUND THEN RETURN ('');
  
  
  END;