alter database datafile 'D:\ORACLEXE\ORADATA\TABLE_NAME.DBF' resize 3769M;

CREATE TABLESPACE TABLE_NAME DATAFILE 
  'C:\app\ADMIN\product\18.0.0\oradata\ORCL\XEPDB1\TABLE_NAME.DBF' SIZE 52M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;

