CREATE OR REPLACE VIEW SEQPA AS 

SELECT SEQ.NUNOTA, SEQ.CODPROD, SEQ.SEQPA, SEQ.USOPROD, SEQ.SEQUENCIA,DENSE_RANK() OVER (ORDER BY SEQ.SEQPA ASC) AS RANK
  FROM (
SELECT ITE.NUNOTA,ITE.CODPROD, ITE.SEQUENCIA AS SEQPA, ITE.USOPROD, ITE.SEQUENCIA
  FROM TGFITE ITE
 WHERE --ITE.NUNOTA=105211 AND
       EXISTS (SELECT 1 FROM TGFVAR VAR WHERE VAR.NUNOTA=ITE.NUNOTA
   AND VAR.NUNOTAORIG=ITE.NUNOTA
   AND VAR.SEQUENCIAORIG=ITE.SEQUENCIA)
   
 UNION ALL
 
 SELECT ITE.NUNOTA,ITE.CODPROD, VAR.SEQUENCIAORIG SEQPA, ITE.USOPROD,ITE.SEQUENCIA
  FROM TGFITE ITE, TGFVAR VAR
 WHERE --ITE.NUNOTA=105211 AND 
       VAR.NUNOTA=ITE.NUNOTA
   AND VAR.NUNOTAORIG=ITE.NUNOTA
   AND VAR.SEQUENCIA=ITE.SEQUENCIA ) SEQ
  ORDER BY SEQ.SEQUENCIA,SEQ.USOPROD DESC